version: '3.8'

services:
  redis:
    container_name: 2023mcs320002_Redis
    image: redis:latest
  

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    container_name: 2023mcs320002_web
    ports:
      - "8080:8081"
    volumes:
      - ./data:/data
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: worker.dockerfile
    container_name: 2023mcs320002_worker
    volumes:
      - ./data:/data
    depends_on:
      - redis